/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package com.ho;

public class App extends Application{
    
    public static void main(String[] args) {
        launch(args);
    }
    
    @Override
    public void start(Stage stage) throws Exception{
        Parent root = FXMLLoader.load(getClass().getResource("/fxml/Scene.fxml"));

        Scene scene = new Scene(root);
        stage.setTitle("JavaFx App");
        stage.setScene(scene);
        stage.show();
    }
}
